version: '3.7'
services:
  app:
    image: laravel:8
    container_name: search-cep-app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
  mysql:
    image: mysql:5.7
    container_name: search-cep-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: search_cep
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
